x-common:
  database:
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    &db-environment
    MYSQL_PASSWORD: &db-password "${DB_PASSWORD}"
    MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  panel: &panel-environment
    HASHIDS_SALT: "${HASHIDS_SALT}"
    HASHIDS_LENGTH: "${HASHIDS_LENGTH}"
    APP_KEY: "${APP_KEY}"
    APP_URL: "${APP_URL}"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "${APP_TIMEZONE}"
    APP_SERVICE_AUTHOR: "${APP_SERVICE_AUTHOR}"
  mail: &mail-environment
    MAIL_FROM: "${MAIL_FROM}"
    MAIL_DRIVER: "${MAIL_DRIVER}"
    MAIL_HOST: "${MAIL_HOST}"
    MAIL_PORT: "${MAIL_PORT}"
    MAIL_USERNAME: "${MAIL_USERNAME}"
    MAIL_PASSWORD: "${MAIL_PASSWORD}"
    MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:

  database:
    image: library/mysql:8.0
    restart: always
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${DATA_DIR}/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  panel:
    image: ghcr.io/pterodactyl/panel:v1.11.10
    restart: always
    networks:
      - pterodactyl
      - local
    links:
      - database
      - cache
    volumes:
      - "${DATA_DIR}/panel/var/:/app/var/"
      - "${DATA_DIR}/panel/logs/:/app/storage/logs"
      - "${DATA_DIR}/panel/nginx/:/etc/nginx/conf.d/"
    environment:
      <<: [ *panel-environment, *mail-environment ]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      TRUSTED_PROXIES: "*"
    labels:
      # HTTP
      - "traefik.http.routers.pterodactyl_panel.entrypoints=web"
      - "traefik.http.routers.pterodactyl_panel.rule=Host(`${PANEL_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl_panel.middlewares=panel_https"
      - "traefik.http.middlewares.panel_https.redirectscheme.scheme=https"
      # HTTPS
      - "traefik.http.routers.pterodactyl_panel-https.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl_panel-https.rule=Host(`${PANEL_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl_panel-https.tls=true"
      - "traefik.http.routers.pterodactyl_panel-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.pterodactyl_panel-https.loadbalancer.server.port=80"

networks:
  local:
    external: false
  pterodactyl:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
